"""Deterministic analytical operations against the crimes schema.

These are NOT generated by an LLM: they are hand-written, parameterized, read-only
SQL run through the same connection pool as the rest of the app (not the restricted
NL-to-SQL role, since these are fixed, reviewed queries rather than arbitrary
user-composed ones). The investigation pipeline calls these for the well-known
analytical shapes (trend/compare/breakdown/anomaly) instead of asking the LLM to
compute them, so every number in a final answer traces back to a query a human wrote
and can review.
"""
from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import text
from sqlalchemy.orm import Session


@dataclass
class AnalyticsResult:
    query_name: str
    sql: str
    rows: list[dict]


def monthly_trend(session: Session, primary_type: str | None = None) -> AnalyticsResult:
    """Crime count per month, optionally filtered to one category — the core
    time-based analysis capability ("how did X change over time")."""
    sql = """
        SELECT date_trunc('month', occurred_at)::date AS month, COUNT(*) AS incident_count
        FROM crimes
        WHERE (:primary_type IS NULL OR primary_type = :primary_type)
        GROUP BY month
        ORDER BY month
    """
    result = session.execute(text(sql), {"primary_type": primary_type})
    rows = [dict(r._mapping) for r in result]
    return AnalyticsResult("monthly_trend", sql, rows)


def top_crime_types(session: Session, limit: int = 10) -> AnalyticsResult:
    """Categorical breakdown: most frequent crime types."""
    sql = """
        SELECT primary_type, COUNT(*) AS incident_count,
               ROUND(100.0 * COUNT(*) FILTER (WHERE arrest) / COUNT(*), 1) AS arrest_rate_pct
        FROM crimes
        GROUP BY primary_type
        ORDER BY incident_count DESC
        LIMIT :limit
    """
    result = session.execute(text(sql), {"limit": limit})
    rows = [dict(r._mapping) for r in result]
    return AnalyticsResult("top_crime_types", sql, rows)


def district_comparison(session: Session) -> AnalyticsResult:
    """Comparison across police districts: volume + arrest rate side by side."""
    sql = """
        SELECT d.code AS district_code, d.name AS district_name,
               COUNT(c.id) AS incident_count,
               ROUND(100.0 * COUNT(c.id) FILTER (WHERE c.arrest) / NULLIF(COUNT(c.id), 0), 1)
                   AS arrest_rate_pct
        FROM police_districts d
        LEFT JOIN crimes c ON c.district_code = d.code
        GROUP BY d.code, d.name
        ORDER BY incident_count DESC
    """
    result = session.execute(text(sql))
    rows = [dict(r._mapping) for r in result]
    return AnalyticsResult("district_comparison", sql, rows)


def community_area_breakdown(session: Session, top_n: int = 15) -> AnalyticsResult:
    """Geographic categorical breakdown by community area."""
    sql = """
        SELECT ca.name AS community_area, COUNT(c.id) AS incident_count
        FROM community_areas ca
        LEFT JOIN crimes c ON c.community_area_code = ca.code
        GROUP BY ca.name
        ORDER BY incident_count DESC
        LIMIT :top_n
    """
    result = session.execute(text(sql), {"top_n": top_n})
    rows = [dict(r._mapping) for r in result]
    return AnalyticsResult("community_area_breakdown", sql, rows)


def monthly_anomalies(session: Session, primary_type: str, z_threshold: float = 2.0) -> AnalyticsResult:
    """Anomaly detection: months whose incident count for a given crime type is more
    than `z_threshold` standard deviations from that type's monthly mean in 2023.
    A plain, explainable z-score — not an LLM guess about what looks "unusual."
    """
    sql = """
        WITH monthly AS (
            SELECT date_trunc('month', occurred_at)::date AS month, COUNT(*) AS incident_count
            FROM crimes
            WHERE primary_type = :primary_type
            GROUP BY month
        ),
        stats AS (
            SELECT AVG(incident_count) AS mean_count, STDDEV_POP(incident_count) AS stddev_count
            FROM monthly
        )
        SELECT m.month, m.incident_count, s.mean_count, s.stddev_count,
               ROUND((m.incident_count - s.mean_count) / NULLIF(s.stddev_count, 0), 2) AS z_score
        FROM monthly m, stats s
        WHERE ABS((m.incident_count - s.mean_count) / NULLIF(s.stddev_count, 0)) >= :z_threshold
        ORDER BY m.month
    """
    result = session.execute(text(sql), {"primary_type": primary_type, "z_threshold": z_threshold})
    rows = [dict(r._mapping) for r in result]
    return AnalyticsResult("monthly_anomalies", sql, rows)


def arrest_rate_by_type(session: Session, limit: int = 15) -> AnalyticsResult:
    """Comparison: arrest rate across crime types (which categories most/least
    often result in an arrest)."""
    sql = """
        SELECT primary_type, COUNT(*) AS incident_count,
               ROUND(100.0 * COUNT(*) FILTER (WHERE arrest) / COUNT(*), 1) AS arrest_rate_pct
        FROM crimes
        GROUP BY primary_type
        HAVING COUNT(*) >= 20
        ORDER BY arrest_rate_pct DESC
        LIMIT :limit
    """
    result = session.execute(text(sql), {"limit": limit})
    rows = [dict(r._mapping) for r in result]
    return AnalyticsResult("arrest_rate_by_type", sql, rows)


def day_of_week_pattern(session: Session, primary_type: str | None = None) -> AnalyticsResult:
    """Time-based analysis: incident volume by day of week."""
    sql = """
        SELECT to_char(occurred_at, 'Day') AS day_of_week,
               EXTRACT(ISODOW FROM occurred_at) AS iso_day_num,
               COUNT(*) AS incident_count
        FROM crimes
        WHERE (:primary_type IS NULL OR primary_type = :primary_type)
        GROUP BY day_of_week, iso_day_num
        ORDER BY iso_day_num
    """
    result = session.execute(text(sql), {"primary_type": primary_type})
    rows = [dict(r._mapping) for r in result]
    return AnalyticsResult("day_of_week_pattern", sql, rows)
